name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Write enviroment to .env file
        uses: thaind0/envfile@v1
        with:
          secrets: ${{ toJson(secrets) }}

      - name: Install dependencies
        run: |
          yarn install

      - name: Build for production
        run: |
          yarn build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CVC_HACKATHON_FRONTEND }}'
          channelId: live
          projectId: cvc-hackathon-frontend
